In [ ]:
from google.colab import files
uploaded=files.upload()

Saving CarPrice_Assignment.csv to CarPrice_Assignment.csv


In [ ]:
import pandas as pd
a=pd.read_csv("CarPrice_Assignment.csv",sep=',')

In [ ]:
a.head()

car_ID  symboling                   CarName  ... citympg highwaympg    price
0       1          3        alfa-romero giulia  ...      21         27  13495.0
1       2          3       alfa-romero stelvio  ...      21         27  16500.0
2       3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3       4          2               audi 100 ls  ...      24         30  13950.0
4       5          2                audi 100ls  ...      18         22  17450.0

[5 rows x 26 columns]

In [ ]:
a.isnull().any()

car_ID              False
symboling           False
CarName             False
fueltype            False
aspiration          False
doornumber          False
carbody             False
drivewheel          False
enginelocation      False
wheelbase           False
carlength           False
carwidth            False
carheight           False
curbweight          False
enginetype          False
cylindernumber      False
enginesize          False
fuelsystem          False
boreratio           False
stroke              False
compressionratio    False
horsepower          False
peakrpm             False
citympg             False
highwaympg          False
price               False
dtype: bool

In [ ]:
a=pd.get_dummies(a)

In [ ]:
a

car_ID  symboling  ...  fuelsystem_spdi  fuelsystem_spfi
0         1          3  ...                0                0
1         2          3  ...                0                0
2         3          1  ...                0                0
3         4          2  ...                0                0
4         5          2  ...                0                0
..      ...        ...  ...              ...              ...
200     201         -1  ...                0                0
201     202         -1  ...                0                0
202     203         -1  ...                0                0
203     204         -1  ...                0                0
204     205         -1  ...                0                0

[205 rows x 201 columns]

In [ ]:
import numpy as np
train=a.iloc[:103]
train_l=train.loc[:,'price']
train_l=np.asarray(train_l)
train_l

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [ ]:
test=a.iloc[103:165]
test_l=test.loc[:,'price']
test_l=np.asarray(test_l)
test_l

array([13499. , 17199. , 19699. , 18399. , 11900. , 13200. , 12440. ,
       13860. , 15580. , 16900. , 16695. , 17075. , 16630. , 17950. ,
       18150. ,  5572. ,  7957. ,  6229. ,  6692. ,  7609. ,  8921. ,
       12764. , 22018. , 32528. , 34028. , 37028. , 31400.5,  9295. ,
        9895. , 11850. , 12170. , 15040. , 15510. , 18150. , 18620. ,
        5118. ,  7053. ,  7603. ,  7126. ,  7775. ,  9960. ,  9233. ,
       11259. ,  7463. , 10198. ,  8013. , 11694. ,  5348. ,  6338. ,
        6488. ,  6918. ,  7898. ,  8778. ,  6938. ,  7198. ,  7898. ,
        7788. ,  7738. ,  8358. ,  9258. ,  8058. ,  8238. ])

In [ ]:
val=a.iloc[165:]
val_l=val.loc[:,'price']
val_l=np.asarray(val_l)
val_l

array([ 9298.,  9538.,  8449.,  9639.,  9989., 11199., 11549., 17669.,
        8948., 10698.,  9988., 10898., 11248., 16558., 15998., 15690.,
       15750.,  7775.,  7975.,  7995.,  8195.,  8495.,  9495.,  9995.,
       11595.,  9980., 13295., 13845., 12290., 12940., 13415., 15985.,
       16515., 18420., 18950., 16845., 19045., 21485., 22470., 22625.])

In [ ]:
train=train.drop(['price'],axis=1)
test=test.drop(['price'],axis=1)
val=val.drop(['price'],axis=1)


In [ ]:
train

car_ID  symboling  ...  fuelsystem_spdi  fuelsystem_spfi
0         1          3  ...                0                0
1         2          3  ...                0                0
2         3          1  ...                0                0
3         4          2  ...                0                0
4         5          2  ...                0                0
..      ...        ...  ...              ...              ...
98       99          2  ...                0                0
99      100          0  ...                0                0
100     101          0  ...                0                0
101     102          0  ...                0                0
102     103          0  ...                0                0

[103 rows x 200 columns]

In [ ]:
val


car_ID  symboling  ...  fuelsystem_spdi  fuelsystem_spfi
165     166          1  ...                0                0
166     167          1  ...                0                0
167     168          2  ...                0                0
168     169          2  ...                0                0
169     170          2  ...                0                0
170     171          2  ...                0                0
171     172          2  ...                0                0
172     173          2  ...                0                0
173     174         -1  ...                0                0
174     175         -1  ...                0                0
175     176         -1  ...                0                0
176     177         -1  ...                0                0
177     178         -1  ...                0                0
178     179          3  ...                0                0
179     180          3  ...                0                0
180     181         -1  ...                0                0
181     182         -1  ...                0                0
182     183          2  ...                0                0
183     184          2  ...                0                0
184     185          2  ...                0                0
185     186          2  ...                0                0
186     187          2  ...                0                0
187     188          2  ...                0                0
188     189          2  ...                0                0
189     190          3  ...                0                0
190     191          3  ...                0                0
191     192          0  ...                0                0
192     193          0  ...                0                0
193     194          0  ...                0                0
194     195         -2  ...                0                0
195     196         -1  ...                0                0
196     197         -2  ...                0                0
197     198         -1  ...                0                0
198     199         -2  ...                0                0
199     200         -1  ...                0                0
200     201         -1  ...                0                0
201     202         -1  ...                0                0
202     203         -1  ...                0                0
203     204         -1  ...                0                0
204     205         -1  ...                0                0

[40 rows x 200 columns]

In [ ]:
from keras import models,layers
model=models.Sequential()
model.add(layers.Dense(10,activation='relu',input_shape=(200,)))
model.add(layers.Dense(8,activation='relu'))
model.add(layers.Dense(6,activation='tanh'))
model.add(layers.D)

In [ ]:
model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])

In [ ]:
al=model.fit(train,train_l,
            batch_size=20,
            epochs=100,
            validation_data=(val,val_l))

Epoch 1/100
6/6 [==============================] - 0s 40ms/step - loss: 279286304.0000 - mae: 13790.6289 - val_loss: 188559904.0000 - val_mae: 13064.6328
Epoch 2/100
6/6 [==============================] - 0s 9ms/step - loss: 279285152.0000 - mae: 13790.5869 - val_loss: 188558720.0000 - val_mae: 13064.5879
Epoch 3/100
6/6 [==============================] - 0s 10ms/step - loss: 279283936.0000 - mae: 13790.5420 - val_loss: 188557696.0000 - val_mae: 13064.5469
Epoch 4/100
6/6 [==============================] - 0s 10ms/step - loss: 279282848.0000 - mae: 13790.5020 - val_loss: 188556624.0000 - val_mae: 13064.5059
Epoch 5/100
6/6 [==============================] - 0s 10ms/step - loss: 279281696.0000 - mae: 13790.4619 - val_loss: 188555632.0000 - val_mae: 13064.4688
Epoch 6/100
6/6 [==============================] - 0s 9ms/step - loss: 279280640.0000 - mae: 13790.4209 - val_loss: 188554528.0000 - val_mae: 13064.4248
Epoch 7/100
6/6 [==============================] - 0s 9ms/step - loss: 2792794